namespace: Default
image:
 repository: ghcr.io/ilkerhalil/weather-forecast
 tag: 1.0.1
 pullPolicy: Always
 containerPort: 80
 env:      
#  - name: ASPNETCORE_ENVIRONMENT
#    value: BETA

imagePullSecrets: regcred

imageCredentials:
  registry: ghcr.io
  username: someone
  password: sillyness
  email: "someone@example.com"

replicaCount: 1

service:
 type: ClusterIP
 port: 5000 

ingress:
 enabled: false
 paths:
 - path: /
   backend:
     serviceName: weather-forecast
     servicePort: 5000
 annotations: 
  kubernetes.io/ingress.class: "nginx"
  nginx.ingress.kubernetes.io/rewrite-target: /
  nginx.ingress.kubernetes.io/proxy-body-size: "0"
 hostName: weather-forecast.formicax.io
     
 tls:

