{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
{{- if .Values.ingress.annotations }}    
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - http:
      paths:
{{- if len (.Values.ingress.paths) }}
{{ tpl (toYaml .Values.ingress.paths | indent 6) . }}
{{- else }}
      - backend:
          serviceName: {{ .Release.Name }}-service
          servicePort: {{ .Values.service.port }}
{{- if .Values.ingress.path }}
        path: {{ .Values.ingress.path }}
{{- end -}}
{{- end -}}
{{- if .Values.ingress.hostName }}
    host: {{ .Values.ingress.hostName | quote }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end }}